server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d8p2s5bsq97s73fk4h6g-a.oregon-postgres.render.com:5432/luxeloop_db
spring.datasource.username=luxeloop_db_user
spring.datasource.password=aepDGvWpvYzFZDR7hZBeVnuKsCn1p6QC
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true